### ISSUE TITLE
InterfaceID Variable is Incorrect

### ISSUE THREAD

**Issue by mrxinu** [solarwinds/orionsdk-python#14]
There's an issue with the example for unmanage where it's not using the right variable name. Will send a PR later today.

**Comment by tonypnode** [comment]
I can take care of it, I'm not working today.

**Comment by mrxinu** [comment]
Thanks!

![bitmoji](https://render.bitstrips.com/v2/cpanel/9990876-171240737_9-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by mrxinu** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10221035-171240737_9-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by mrxinu** [comment]
Whoops, didn't mean to close this. Doing too many things at once.

**Comment by tonypnode** [comment]
np. pr sent.

**Comment by tonypnode** [comment]
done and merged, you can close this issue now.
