### ISSUE TITLE
IPAM Get next available IP from subnet

### ISSUE THREAD

**Issue by tonypnode** [solarwinds/orionsdk-python#19]
If someone already has an example using the IPAM API (via python) to get the next available IP address from a specified subnet, please add, otherwise, I'll start working on it and get a PR in soon.

**Comment by tdanner** [comment]
I don't believe we have sample code for this in Python. If you want a PowerShell version to refer to, there's one in the PowerOrion module: https://github.com/solarwinds/OrionSDK/blob/master/Samples/PowerShell/PowerOrion/PowerOrion.psm1#L1107

**Comment by dkhenderson2** [comment]
This will do what you are looking for:

import requests
from orionsdk import SwisClient

npm_server = 'Server ip'
username = 'domain\username'
password = 'password'

verify = False
if not verify:
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)


swis = SwisClient(npm_server, username, password)

ipaddr = swis.invoke('IPAM.SubnetManagement', 'GetFirstAvailableIp', "172.25.0.0", "23")

if ipaddr == "Not found":
	print("Subnet doesnot exist")
else:
	print(ipaddr)
