### ISSUE TITLE
using SDK Python to find ACL

### ISSUE THREAD

**Issue by newscriptkid** [solarwinds/orionsdk-python#22]
Hi,
Is there a method utilising the SDK to find which devices have a certain ACL, for example access-list 101?
Thanks

**Comment by tdanner** [comment]
Yes, this is possible with NCM. You can do a full text search of the configs using `Cirrus.ConfigArchive.ConfigSearch`. See https://github.com/solarwinds/OrionSDK/wiki/NCM-Config-Search for how to use this. That will return a list of the IDs of configs that match your search. You can then query `Cirrus.ConfigArchive` to find out which nodes those configs came from.

**Comment by newscriptkid** [comment]
Hi Tim,
Thanks for that,

I'm new to all this, 

My syntax is:
'''
https://10.110.29.31:17778/SolarWinds/InformationService/v3/Json/Query?query=SELECT Caption, string[] ConfigSearch(string searchString = access-list 199, string configType = null, 
    string coreNodeIdList = null, bool matchWholeWord = true, bool searchOnlyMostRecent = false,
    DateTime? startTime = null, DateTime? endTime = null)
'''
and im getting the following error:

'''
{"Message":"no viable alternative at input '' in Select clause","ExceptionType":"SolarWinds.Data.SWQL.SWQLSyntaxException","FullException":"SolarWinds.Data.SWQL.SWQLSyntaxException: no viable alternative at input '' in Select clause ---> Antlr.Runtime.NoViableAltException: A recognition error occurred.\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.relationalExpression()\u000d\u000a   --- End of inner exception stack trace ---\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.relationalExpression()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.equalityExpression()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.negatedExpression()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.logicalAndExpression()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.logicalOrExpression()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.expression()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.aliasedExpression()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.selectedPropertiesList()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.selectClause()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.selectFrom()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.queryRule()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.selectStatement()\u000d\u000a   at SolarWinds.Data.SWQL.Parser.SWQLParser.statement()\u000d\u000a   at SolarWinds.Data.SWQL.SWQLParser.Parse(String query)\u000d\u000a   at SolarWinds.Data.Query.Engine.QueryProcessor.ProcessInternal(String query, IQueryExecutionContext context)\u000d\u000a   at SolarWinds.InformationService.Core.QueryPlanCache.GetQueryPlan(String query, String username, Boolean federationEnabled, Func`1 buildQueryPlan)\u000d\u000a   at SolarWinds.InformationService.Core.InformationService.RunQuery(String query, IDictionary`2 parameters, IDataSerializer serializer)"}

'''
Any ideas?

Thanks

**Comment by newscriptkid** [comment]
I've changed the syntax to the below and get same error but now i can see my search string in the error:

```
SELECT Caption, string[access-list 199] ConfigSearch(string searchString = true, string configType = null, 
    string coreNodeIdList = null, bool matchWholeWord = true, bool searchOnlyMostRecent = false,
    DateTime? startTime = null, DateTime? endTime = null)
```
error message im getting:

```
{
    "Message": "no viable alternative at input 'access-list 199' in Select clause",
    "ExceptionType": "SolarWinds.Data.SWQL.SWQLSyntaxException",
    "FullException": "SolarWinds.Data.SWQL.SWQLSyntaxException: no viable alternative at input 'access-list 199' in Select clause ---> Antlr.Runtime.NoViableAltException: A recognition error occurred.\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.relationalExpression()\r\n   --- End of inner exception stack trace ---\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.relationalExpression()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.equalityExpression()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.negatedExpression()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.logicalAndExpression()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.logicalOrExpression()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.expression()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.aliasedExpression()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.selectedPropertiesList()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.selectClause()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.selectFrom()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.queryRule()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.selectStatement()\r\n   at SolarWinds.Data.SWQL.Parser.SWQLParser.statement()\r\n   at SolarWinds.Data.SWQL.SWQLParser.Parse(String query)\r\n   at SolarWinds.Data.Query.Engine.QueryProcessor.ProcessInternal(String query, IQueryExecutionContext context)\r\n   at SolarWinds.InformationService.Core.QueryPlanCache.GetQueryPlan(String query, String username, Boolean federationEnabled, Func`1 buildQueryPlan)\r\n   at SolarWinds.InformationService.Core.InformationService.RunQuery(String query, IDictionary`2 parameters, IDataSerializer serializer)"
}
```

**Comment by tdanner** [comment]
This is a verb, not a query, so the URL format would be based on this: https://github.com/solarwinds/OrionSDK/wiki/REST#invoke-request

```
https://x.x.x.x:17778/SolarWinds/InformationService/v3/Json/Invoke/Cirrus.ConfigArchive/ConfigSearch
```

It needs to be a POST request with a json array in the body. Like this:

```
["access-list 1999", "Running", null, true, true]
```

**Comment by newscriptkid** [comment]
Hi Tim,

Is there a document that covers the whole Solarwinds API feature for beginners?

It's still not working for me - i've done the following in postman:



[cid:be0405a5-f86b-4218-af35-92f30ca98371]

If the above image is not showing up below is the details:

URL: https://10.110.29.31:17778/SolarWinds/InformationService/v3/Json/Invoke/Cirrus.ConfigArchive/ConfigSearch

<https://10.110.29.31:17778/SolarWinds/InformationService/v3/Json/Invoke/Cirrus.ConfigArchive/ConfigSearch>in the 'Key' field: I've typed in "verb" over here

in the 'Value' field: I've typed in ["access-list 199", "Running", null, true, true]

The complete URL after the above is:

https://10.110.29.31:17778/SolarWinds/InformationService/v3/Json/Invoke/Cirrus.ConfigArchive/ConfigSearch?verb=["access-list 199", "Running", null, true, true]

In postman i am getting the following error:

"The body of the message cannot be read because it is empty."

However if i type that url in a browser i get the following error:


{"Message":"Invalid SWIS uri at character 40: Incomplete uri. Parser did not finish in End state, but instead was left in Scheme state\u000d\u000aParameter name: uri","ExceptionType":"System.ArgumentException","FullException":"System.ArgumentException: Invalid SWIS uri at character 40: Incomplete uri. Parser did not finish in End state, but instead was left in Scheme state\u000d\u000aParameter name: uri\u000d\u000a   at SolarWinds.Data.Utility.SwisUriParser.ParsingError(String message)\u000d\u000a   at SolarWinds.Data.Utility.SwisUriParser.ParseInternal()\u000d\u000a   at SolarWinds.InformationService.Core.InformationService.Read(String uri)"}

________________________________

**Comment by newscriptkid** [comment]
Hi Tim,

Is there a solarwinds doc that covers API for beginners?

It's still not working for me, please see the pic:
![postman](https://user-images.githubusercontent.com/36821056/38413003-6fb88750-3982-11e8-8d1b-adb1a9464b33.PNG)

I've entered the initial URL (with POST):
```
https://10.110.29.31:17778/SolarWinds/InformationService/v3/Json/Invoke/Cirrus.ConfigArchive/ConfigSearch
```

**Comment by newscriptkid** [comment]
Hi Tim,

Is there any Solarwinds documentation that covers API for beginners?

Also its giving me an output but in a weird format and it only gives me output if i select:
```
JSON(application/json)
```
See picture:

![postman](https://user-images.githubusercontent.com/36821056/38414419-5514feb6-3986-11e8-9179-4537037fce74.PNG)

![postman2](https://user-images.githubusercontent.com/36821056/38414532-ae196ed4-3986-11e8-9500-b5e4ed4a98b4.PNG)

**Comment by tdanner** [comment]
The API requires that requests come with a `Content-Type: application/json` header, which is what that postman option provides.

Yes, this format is a bit weird. Honestly I don't know why the IDs are wrapped in `'` inside the strings. Nevertheless, those are the config ids and if you unwrap them you can query `Cirrus.ConfigArchive` to map them back to the devices those configs came from.

**Comment by newscriptkid** [comment]
Thanks,

Is there any documentation that explains all this unwrapping stuff and guide on solarwind api?

This is getting really confusing maybe because as of yet I don't understand how it all works hence looking for documentation.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tdanner** [comment]
The primary documentation is on the GitHub wiki for the OrionSDK project: https://github.com/solarwinds/OrionSDK/wiki

If you are just getting started, you might it helpful to watch some of the videos. Just go to youtube and search for "solarwinds api".

And the best place for "how do I...?" questions is not github issues but the SolarWinds customer forum: https://thwack.solarwinds.com/community/labs_tht/orion-sdk
