### ISSUE TITLE
groups.py Custom Properties filter

### ISSUE THREAD

**Issue by cberg2048** [solarwinds/orionsdk-python#26]
When attempting to add group members in the manner below, Site being a node custom property, the filter returns all nodes in the system, and all nodes are added to the group. 

# group members
[
{'Name':  site,   'Definition': "filter:/Orion.Nodes[Site={0}]".format(site)},
]

When I look at the dynamic query in the GUI I see that the conditions are set for Address, which is another custom property, is, then the value for my site variable. I am not sure why this matches all nodes in the system.  

Any insight into how I might be able to filter with custom properties would be greatly appreciated.

**Comment by tdanner** [comment]
To filter by the custom property `Site`, use this syntax:

`filter:/Orion.Nodes[CustomProperties.Site='{0}']`

**Comment by cberg2048** [comment]
Thank you!

Additionally, is there a way to create nested groups via the API? Or in other words, add members that are already groups?

**Comment by tdanner** [comment]
The corresponding PowerShell sample shows several other variations, including adding a group to a group. Let me know if you have any questions about translating that to python.

https://github.com/solarwinds/OrionSDK/blob/master/Samples/PowerShell/Groups.ps1

**Comment by danjagnow** [comment]
This question has been answered, so I am closing the issue.  Please feel free to reopen if there are follow-up questions.
