### ISSUE TITLE
ValueError:  No Json object could be decoded

### ISSUE THREAD

**Issue by tadeos** [solarwinds/orionsdk-python#3]
Hi All,
I was just testing the water to get some data through Orionsdk.. but i am getting ValueError: No Json Object could be decoded error.  below the full code and  compelete stackTrace... 
Please let me know what the issue is:
import json
import requests
from orionsdk import SwisClient

verify = False
if not verify:
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

swis = SwisClient(npm_server, username, password)
print swis.query("SELECT TOP 3 NodeID, DisplayName FROM Orion.Nodes")

StackTrace:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\orionsdk\swisclient.py", line 24, in query

```
{'query': query, 'parameters': params}).json()
```

  File "C:\Python27\lib\site-packages\requests\models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by tdanner** [comment]
You are getting some kind of error from the server, but this doesn't really tell us what the problem is. It could be a bad username/password.

I just pushed a change to this code that will cause it to throw an exception when the server returns an error instead of mindlessly trying to parse the error as JSON.

**Comment by tadeos** [comment]
Hi Tim, 
Thanx for the response and quick update.  I used your update and the finding is ,  you are right, i am getting 403 back from the server.  
I could login to the web console without any issue, so why would it forbid me from accessing it?? perhaps cert issue??

**Comment by tdanner** [comment]
It it were a certificate issue, you would not get any HTTP response code at all. Try making an API request using a tool like Postman to see if you get the same error.

**Comment by tadeos** [comment]
Thanks Tim,

I tried rewriting the SwisClient calss with noting but a http connection method and a request method.. and it still gives me the 403.  may be my account is not set up to access the service ?? https://22.222.22.222:17778/SolarWinds/InformationService/v3/Json?

**Comment by tadeos** [comment]
I tried that, but it doesn't look like there is any entry coming for my requests...  last entry to the logs is dated as yesterday.  all my tries that I did today, did not make to the log.  I did conclude that that wasn't the right log until you mentioned it above.

**Comment by tdanner** [comment]
Give Postman (https://www.getpostman.com/) a try and see if that works.

**Comment by bewing** [comment]
> I just pushed a change to this code that will cause it to throw an exception when the server returns an error instead of mindlessly trying to parse the error as JSON.

When/if will 0.0.5 be published to pypi containing this change?

**Comment by joshclark** [comment]
0.0.6 published 
https://pypi.python.org/pypi/orionsdk

**Comment by tdanner** [comment]
Closing stale issue.
