### ISSUE TITLE
Why is there a hard coded port in the url?

### ISSUE THREAD

**Issue by andrew80k** [solarwinds/orionsdk-python#30]
Can someone explain to me why there is a hardcoded port in the url?  My solarwinds runs on a different port and now I have to hack the code to make it work...

**Comment by tdanner** [comment]
The port for the API (default 17778) is different from the website port (default 80 or 443). Have you actually changed the API port?

**Comment by andrew80k** [comment]
Yes, unfortunately, it seems so.  Not my installation, I'm just trying to leverage it.

**Comment by andrew80k** [comment]
So, It appears I was mistaken... :/ it was only blocked by firewall rules...  I still think the port should be configurable, unless orion can't be configured on a different port...  Closing this anyway...
