### ISSUE TITLE
the orionsdk pypi package is at version 0.0.6 and more than 1 year out of date on pypi.org

### ISSUE THREAD

**Issue by serbant** [solarwinds/orionsdk-python#31]
... but the documentation on the github age applies to version 0.0.8. if one installs the sdk via pip (as documented) and then one tries to use the exposed session object, one gets an exception.

![image](https://user-images.githubusercontent.com/1781964/53128588-0fae1700-351a-11e9-83c7-067bf6cacac4.png)

**Comment by atxviking** [comment]
This is getting to be problematic. Please address soon, if possible. 
Willing to help should you want it.

**Comment by atxviking** [comment]
In the mean time, put the below line into your requirements.txt file and pip will install the most recent version. At least it did for me. I make no guarantees about this. 

```
git+https://github.com/solarwinds/orionsdk-python
```

**Comment by serbant** [comment]
one must be careful if one uses this trick because when 'freezing' the
environment back to requirements.txt, the version of the installed package
is saved and the git+https line will be lost.

**Comment by AlexanderBeetle** [comment]
I got bit also by the pypi version being old and things not working because I was reading the docs from github. bump :)

**Comment by danjagnow** [comment]
Version 0.1.0 is now available at https://pypi.org/project/orionsdk/.

**Comment by AlexanderBeetle** [comment]
Thank you!
