### ISSUE TITLE
Orionsdk swisclient: CPU and memory resource stats and monitoring

### ISSUE THREAD

**Issue by AmbicaY** [solarwinds/orionsdk-python#33]
Here is a small code snippet that I use to add a node for monitoring:

    res = client.create('Orion.Nodes', **props)

    nodeid = re.search(r'(\d+)$', res).group(0)

    for k,v in custom_props.items():
        client.update(res+'/CustomProperties',**{k: v})

    client.invoke('Orion.HardwareHealth.HardwareInfo', 'EnableHardwareHealth', 'N:'+nodeid, 9)

    _add_pollers(client, nodeid, 'default')
    _add_pollers(client, nodeid, poller_template)

    client.invoke('Orion.Nodes', 'PollNow', 'N:'+nodeid )

Even after I invoked HardwareInfo, my CPU and Memory stats are not getting collected.

To be precise, in NPM, when you click the link "list resources" on the node page, it enumerates all the hardware and interfaces details. There were select CPU and memory for stats collection. I want to achieve the same through code.

What am I missing?

**Comment by AmbicaY** [comment]
@tdanner can you help?

**Comment by danjagnow** [comment]
What kind of node are you monitoring?  9 is the code for the **SnmpCisco** polling method.  See the (Hardware Health)[https://github.com/solarwinds/OrionSDK/wiki/Hardware-Health] page on the Orion SDK wiki for additional details about the options.

**Comment by AmbicaY** [comment]
Its a network device. Infact a cisco switch. I referred that page, hence used 9 in my code. 

But I am not sure how to enable CPU and Mem monitoring/stats collection.

**Comment by nothrow** [comment]
Hi,

unfortunately, HardwareHealth and SNMP/CPU polling are implemented in pretty different manner. 
For SNMP/CPU polling, you need to add proper pollers to the Orion.Pollers entity. That could be tricky - there are many of them applicable for Cisco SNMP devices, and I can't tell which one to enable.

Orion detects them during inventory step - I'm not sure if it happens during adding node in import. You can check on your own:

`SELECT PollerType, Enabled FROM Orion.Pollers WHERE PollerType LIKE 'N.CPU.SNMP.%' AND NetObjectType='N' AND NetObjectId=@your_node_id`.

This returns something like 'N.CPU.SNMP.HrProcessorLoad' (for my windows machine). If it is disabled, you can just update the entity, set Enabled to true, and you're good. Same goes for 'N.Memory.%' poller.

In the case they are not there, you need to enforce Inventory re-run. 

_note: these steps are undocumented, and may change or stop working any time in the future._

There is Orion.NodeSettings entity, which is - pretty much - key-value pair store for nodes.

And the magic here is to add key 'Core.NeedsInventory' with value 'Cpu:Memory'. Orion then should re-run the inventory job, populating pollers table.

**Comment by AmbicaY** [comment]
Hey nothrow, 

What exactly is this inventory job? Anyway to trigger it through code?

Regards,
Ambica

**Comment by nothrow** [comment]
You can add, using create operation, key:value `Core.NeedsInventory` : `Cpu:Memory`, with proper NodeId, to `Orion.NodeSettings` entity.

**Comment by AmbicaY** [comment]
tried it, still does not help.

May be this is not applicable for cisco switches?

For interfaces, we can invoke DiscoverInterfacesOnNode on Orion.NPM.Interfaces entity and then we can add whatever pollers we need. But we dont have any entity related to CPU or Memory or other resources? How is the listresources.aspx working?

**Comment by nothrow** [comment]
> How is the listresources.aspx working?

Kind of black magic. It calls some local WebAPI endpoints, and does lot of pre/postprocessing. It is not straightforward to use, and cannot be used as public API.

> But we dont have any entity related to CPU or Memory or other resources? 

Not at this moment. `DiscoverInterfacesOnNode` were kind of hacked in just for one specific purpose per request.

> May be this is not applicable for cisco switches?

WorksForMe(tm). But it is not immediate, it takes some time.

Steps I've taken:
- I deleted all pollers from the Orion.Pollers entity for given node.
- I added proper NodeSetting value:
- Waited for few minutes (10 minutes is the background inventory checker default interval. It can be reduced from settings)
- Pollers reappear

```
import requests
from orionsdk import SwisClient

server = 'localhost'
username = 'admin'
password = ''

from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

swis = SwisClient(server, username, password)

pollers = swis.query("SELECT PollerType, Uri FROM Orion.Pollers WHERE NetObjectID = 1003")

for row in pollers['results']:
    print("Deleting poller {PollerType}".format(**row))
    swis.delete(row['Uri'])

print("Adding nodesetting")
props = {
    'NodeID': 1003,
    'SettingName': 'Core.NeedsInventory',
    'SettingValue': 'Cpu:Memory'
}

results = swis.create('Orion.NodeSettings', **props)

print("wait for 15 minutes (interval of background inventory check)")
```

Output:

```
Deleting poller N.Status.ICMP.Native
Deleting poller N.Status.SNMP.Native
Deleting poller N.ResponseTime.ICMP.Native
Deleting poller N.ResponseTime.SNMP.Native
Deleting poller N.Details.SNMP.Generic
Deleting poller N.Uptime.SNMP.Generic
Deleting poller N.Cpu.SNMP.CiscoGen3
Deleting poller N.Memory.SNMP.CiscoGen3
Deleting poller N.Routing.SNMP.Ipv4CidrRoutingTable
Deleting poller N.RoutingNeighbor.SNMP.BGP
Deleting poller N.Topology_Vlans.SNMP.VtpVlan
Deleting poller N.Topology_CDP.SNMP.cdpCacheTable
Deleting poller N.Topology_Layer3.SNMP.ipNetToMedia
Deleting poller N.Topology_Layer3_IpRouting.SNMP.rolesRouter
Deleting poller N.Topology_Layer3_IpRouting.SNMP.ipCidrRouter
Adding nodesetting
wait for 15 minutes (interval of background inventory check)
```

after few minutes the line from Orion.NodeSettings disappear, and pollers appear:

```
import requests
from orionsdk import SwisClient

server = 'localhost'
username = 'admin'
password = ''

from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

swis = SwisClient(server, username, password)

pollers = swis.query("SELECT PollerType, Enabled FROM Orion.Pollers WHERE NetObjectID = 1003")

for row in pollers['results']:
    print("Poller: {PollerType}:{Enabled}".format(**row))

```

: 

```
Poller: N.Cpu.SNMP.CiscoGen3:True
Poller: N.Memory.SNMP.CiscoGen3:True
```


Note: it takes some time. 

Note2: please, do not delete all pollers on production server. The code with delete was meant only as an example.

**Comment by nothrow** [comment]
You can also check that everything works correctly in logs.

"c:\Users\All Users\SolarWinds\Logs\Orion\Core.BusinessLayer.log" 

```
2019-05-16 14:03:27,769 [STP SmartThreadPool Thread #1] INFO  SolarWinds.Orion.Core.BusinessLayer.BackgroundInventoryManager - (null)  Starting inventorying of Node 1003, NeedsInventory = 'Cpu:Memory'
2019-05-16 14:03:28,966 [STP SmartThreadPool Thread #1] INFO  SolarWinds.Orion.Core.BusinessLayer.BackgroundInventoryManager - (null)  Inventorying of Node 1003 completed in 1213ms.
2019-05-16 14:03:28,966 [STP SmartThreadPool Thread #1] INFO  SolarWinds.Orion.Core.BusinessLayer.BackgroundInventoryManager - (null)  Background Inventorying Finished
```

**Comment by danjagnow** [comment]
This question has been answered, and there hasn't been any recent conversation on this thread, so I am closing this issue for now.  Feel free to re-open the issue if additional information is needed.
