### ISSUE TITLE
Unable to invoke on Alert Suppression

### ISSUE THREAD

**Issue by superadm1n** [solarwinds/orionsdk-python#34]
I am trying to utilize the invoke method to get the alert suppression state, suppress alerts, and resume alerts for a node. When the invoke method gets run it raises an http error:

requests.exceptions.HTTPError: 400 Client Error: Verb Orion.AlertSuppression.ResumeAlerts cannot unpackage parameter 0 with type System.String[] for url: https://orion.servername.com:17778/SolarWinds/InformationService/v3/Json/Invoke/Orion.AlertSuppression/ResumeAlerts

An example that fails is this script below
```python
import orionsdk
import datetime

sw = orionsdk.SwisClient('server', 'username', 'password')
uri = sw.query("SELECT Uri FROM Orion.Nodes WHERE NodeID=@node_id", node_id=1179)['results'][0]['Uri']

# get suppression State fails
sw.invoke('Orion.AlertSuppression', 'GetAlertSuppressionState', uri)

# suppressing alerts fails
sw.invoke('Orion.AlertSuppression', 'SuppressAlerts', uri, datetime.datetime.now(), None)

# resume alerts fails
sw.invoke('Orion.AlertSuppression', 'ResumeAlerts', uri)

```
I have validate that the username + password I am using allows me to do other things via the API and when I manually paste the URI into SWQL studio doing an invoke on GetAlertSuppressionState it does return data.

Im not sure what I am doing wrong.

**Comment by superadm1n** [comment]
After doing some research on .NET based on the error message that was being returned from the server looking for System.String[] i submitted the Node URI in a list and it was successful. Below is a verson of the script that works successfully.

```python
import orionsdk
import datetime

sw = orionsdk.SwisClient('server', 'username', 'password')
uri = sw.query("SELECT Uri FROM Orion.Nodes WHERE NodeID=@node_id", node_id=1179)['results'][0]['Uri']

# get suppression State works
sw.invoke('Orion.AlertSuppression', 'GetAlertSuppressionState', [uri])

# suppressing alerts works
sw.invoke('Orion.AlertSuppression', 'SuppressAlerts', [uri], datetime.datetime.now(), None)

# resume alerts works
sw.invoke('Orion.AlertSuppression', 'ResumeAlerts', [uri])

```

**Comment by danjagnow** [comment]
I'm closing this issue since you've captured this documentation in the sample scripts in #35.
