### ISSUE TITLE
Creating Alerts?

### ISSUE THREAD

**Issue by sephethus** [solarwinds/orionsdk-python#36]
Is there or will there be a way to create alerts and application monitors using this python SDK or is there another one that does this?

**Comment by mrxinu** [comment]
Alerts don't support CRUD operations and there's no verb for them so you're down to doing the import/export thing. If you exported an alert you liked, and then figured out what parts of the XML would have to be customized, you could use the Import verb to import the XML file.

Run this SWQL query and have a look at the results:

```sql
SELECT EntityName, VerbName, Position, Name, Type, XmlTemplate, XmlSchemas, IsOptional
FROM Metadata.VerbArgument
WHERE EntityName = 'Orion.AlertConfigurations'
AND VerbName IN ('Import', 'Export')
```

**Comment by danjagnow** [comment]
This question has been answered, so I'm closing this issue.  Feel free to reopen if there are follow-up questions.

**Comment by mammuthus** [comment]
Could you please give some example how to import XML alert with python?

**Comment by mrxinu** [comment]
Hey @mammuthus, I'm looking at the example you referenced and I'm concerned that you're not passing a single-element list like the API requires. The shape of the JSON body should be like this:
```json
["xml here"]
```
What you're getting by passing the XML body on its own is this:
```json
xml here
```
Or possibly:
```json
"xml here"
```

**Comment by mammuthus** [comment]
@mrxinu, thank you for answer! Actually I do as example suggests:
`importfile = 'my_alert.xml'`

```
with open(importfile, 'r') as f:
        alert = f.read()
        results = swis.invoke('Orion.AlertConfigurations', 'Import', alert)
        print(results)
```
Where is my mistake? :(

**Comment by mrxinu** [comment]
Sorry @mammuthus, what I'm saying the example is wrong. I'm in the middle of some work with a client, but I'll create a pull request to update the code so it works tomorrow morning.

**Comment by mammuthus** [comment]
Thank you, @mrxinu!

**Comment by mrxinu** [comment]
Actually, it looks like it does work. Can you send me the XML file you're trying to import?

**Comment by mammuthus** [comment]
@mrxinu Yes, that's it: https://gist.github.com/mammuthus/ce3ea4766e9c7332bf37b027d5af0f16

**Comment by mrxinu** [comment]
Ah okay, I found the problem. The reset condition references an application that doesn't exist. If you replace that portion of the XML with the default (reset when the condition is no longer true) it imports just fine.

`swis://ourswsserver/Orion/Orion.Nodes/NodeID=455/Applications/ApplicationID=1029`

Here's a fork of your XML with the changes:

https://gist.github.com/mrxinu/5746b41299fb7b12739a983f3ba23269

**Comment by mammuthus** [comment]
@mrxinu But application is exist :( 
node: `/Orion/NetPerfMon/NodeDetails.aspx?NetObject=N:455`
app: `/Orion/APM/ApplicationDetails.aspx?NetObject=AA:1029`
And this app is attached to the node.

**Comment by mrxinu** [comment]
I can help you whittle it down a little further if you want on a Webex if you're available early next week.

**Comment by mammuthus** [comment]
@mrxinu It would be great
