### ISSUE TITLE
Bulk Group creation with dynamic query

### ISSUE THREAD

**Issue by adamconda** [solarwinds/orionsdk-python#38]
Does anyone know the correct syntax for creating dynamic query with a filter using a variable (sitecode) contained in the DNS name:

"filter:/Orion.Nodes[Contains(DNS,sitecode)]"

I can use a string here, not sure how to add a variable

**Comment by mrxinu** [comment]
Honestly I create one in the application and then copy it out of the table's definition field.

**Comment by adamconda** [comment]
I just needed to insert variable into the string:

"filter:/Orion.Nodes[Contains(DNS, " + sitecode + ")]"

**Comment by mrxinu** [comment]
Thanks for letting us know!
![bitmoji](https://render.bitstrips.com/v2/cpanel/22000569-5d25-4396-89f3-df67eb24ea30-5a2192cb-6188-4e5c-a482-ea7978b8a7e5-v1.png?transparent=1&palette=1&width=246)
