### ISSUE TITLE
Solarwinds Class File

### ISSUE THREAD

**Issue by oniram22** [solarwinds/orionsdk-python#39]
I'm about to submit a pull request for a solarwinds class file I've been working on.  It basically let's you supply the IP, username and password for your SolarWinds NPM instance and then has an array of methods you can call to make updates to your system.  However the real power of the class is that all of the method calls are done using nothing more than the human readable names that are used throughout the GUI.  All of the ID's, URI's, and SQL calls are abstracted out and done behind the scenes.  The thought process is that this creates a lower bar for entry into Solarwinds programmability.  You are able to get started updating your system programmatically without having to have a detailed knowledge of the inner workings of Solarwinds.  What I'm uploading is an initial draft based on some activities we're doing in house.  The hope would be to grow the class file over time as additional needs surfaced form the community.  Also, given the file is a python class file it's call __init__.py but should really be placed in a directory called 'solarwinds'.  I wasn't sure how to make that happen within the github repository and the rights I have.  Feel free to rearrange that.

**Comment by mrxinu** [comment]
This is so exciting! Tagging @tdanner about the repository details. We had to do something similar with the SwisClient to so it could be loaded via pip.

**Comment by oniram22** [comment]
Yeah, you read my mind.  We'd somehow have to make it a pip package that could be installed and imported.  I haven't had to do that yet but if you need me to research how that works, just let me know.  Thanks.

**Comment by danjagnow** [comment]
I merged the pull request, but then I noticed that this is in the **samples** folder.  I'm thinking we should move this over to the **orionsdk** folder as **solarwinds.py** and import it in **__init__.py** like we're doing for the `SwisClient` class.  The `orionsdk` namespace makes more sense.

**Comment by oniram22** [comment]
Yeah, agreed the structure as it is doesn’t work quite right the way we have it now.  We could either handle it as part of the orionsdk like you’re saying.  Or we can could spin it out to its own separate git repository.  Either way works for me.  Whatever your preference is.

Michael J. Marino
Assistant Director of Network Services
Morgan, Lewis & Bockius LLP
1701 Market Street | Philadelphia, PA 19103-2921
Direct: +1.215.963.4658<tel:+1.215.963.4658> | Main: +1.215.963.5000<tel:+1.215.963.5000> | Fax: +1.215.963.5001<tel:+1.215.963.5001>
michael.marino@morganlewis.com<mailto:michael.marino@morganlewis.com> | www.morganlewis.com<http://www.morganlewis.com/>

**Comment by danjagnow** [comment]
v0.3.0 has now been released with the new `SolarWinds` class in the `orionsdk` namespace.

**Comment by oniram22** [comment]
On a side note, I’m not sure if you have any influence or control over what SWIS verbs are made available but had two items that I was looking to automate and couldn’t.  I created the feature requests below on Thwack for the actions.  If there’s anything you can do to push it on your end it would be appreciated.  I’d love to add them to the SolarWinds package as well.  We just need the underlying SWIS ability in place.  Thanks.

https://thwack.solarwinds.com/ideas/11388

https://thwack.solarwinds.com/ideas/11389

Michael J. Marino
Assistant Director of Network Services
Morgan, Lewis & Bockius LLP
1701 Market Street | Philadelphia, PA 19103-2921
Direct: +1.215.963.4658<tel:+1.215.963.4658> | Main: +1.215.963.5000<tel:+1.215.963.5000> | Fax: +1.215.963.5001<tel:+1.215.963.5001>
michael.marino@morganlewis.com<mailto:michael.marino@morganlewis.com> | www.morganlewis.com<http://www.morganlewis.com/>
