### ISSUE TITLE
Python error raised from SWIS error should include details

### ISSUE THREAD

**Issue by tdanner** [solarwinds/orionsdk-python#4]
When a call to SWIS throws an error (HTTP 4xx or 5xx), the python client raises an error. In these cases, the SWIS response includes a json-encoded object with some details about the cause of the error. Including these details in the python error object would help users understand and resolve the problem.

**Comment by TomasVrabel** [comment]
I created pull request with fix.

For HTTP errors 4xx and 5xx client tries to extract detail message that was sent by server.
This message is populated to exception in Python.

**Comment by tdanner** [comment]
Closed by merging pull request #5
