### ISSUE TITLE
Issue with Updating Custom Properties 

### ISSUE THREAD

**Issue by jamesainslie** [solarwinds/orionsdk-python#57]
The sample code shows this: 

```
swis.update(uri + '/CustomProperties', City='Austin')

```

But when I:

```
property = 'City'
value = 'Austin'
props = { property : value }

swis.update(uri + '/CustomProperties', props)
```

The update fails with:
```
Traceback (most recent call last):
File "./custom_property_update.py", line 67, in <module>
update_props(hostid, prop, value)
File "./custom_property_update.py", line 43, in update_props
swis.update(uri + '/CustomProperties', {prop:value} )
TypeError: update() takes exactly 2 arguments (3 given)

```

Can somebody help?

**Comment by mrxinu** [comment]
Looks like you sorted it out here? https://thwack.solarwinds.com/t5/Orion-SDK-Discussions/Updating-multiple-custom-properties-from-a-list/m-p/612215#M10910

Okay to close?

**Comment by jamesainslie** [comment]
No, I posted here because I have not received a response on THWAK. The response is exactly what I am trying to do; ie. Pass a dict as the second argument. But the SDK barfs claiming I am giving it three.

**Comment by mrxinu** [comment]
Ah okay - I saw the thread marked as solved but didn't realize it wasn't your thread. I'll have a look.

**Comment by mrxinu** [comment]
Oops, I see what happened. You're passing a dict to a method that's expecting **kwargs. You have to prepend `**` to your dictionary to unpack it on the way in.

```python
property = 'City'
value = 'Austin'
props = { property : value }

swis.update(uri + '/CustomProperties', **props)
```

**Comment by jamesainslie** [comment]
doh! Thanks so much. Couldn't see the forest for the trees. You rock!

**Comment by mrxinu** [comment]
You're welcome! I'm glad it helped!
