### ISSUE TITLE
Unable to find poller_type for creating node

### ISSUE THREAD

**Issue by goutham-kumar** [solarwinds/orionsdk-python#58]
add_node.py sample expects "poller_type" while trying to insert a new node into orion. Could any please guide how to get poller_types for new node.

**Comment by danjagnow** [comment]
> Could any please guide how to get poller_types for new node.

There is a list of [poller types](https://github.com/solarwinds/OrionSDK/wiki/Poller-Types) on the Orion SDK wiki.  For your own environment, you can also query `Orion.Pollers` to find all the `PollerType` values that are in use.  Here is a [SWQL](https://github.com/solarwinds/OrionSDK/wiki) (not SQL) query:

```sql
SELECT DISTINCT(PollerType)
FROM Orion.Pollers
ORDER BY PollerType
```

**Comment by goutham-kumar** [comment]
Thanks for the reply, poller type cannot be same for every node right, how can I filter the poller types wit the existing ones.

**Comment by danjagnow** [comment]
> Thanks for the reply, poller type cannot be same for every node right, how can I filter the poller types wit the existing ones.

I'm not sure that I completely understand your question.  The sample script [add_node.py](https://github.com/solarwinds/orionsdk-python/blob/97168451ddbc68db1773717f592a42f78be0eefe/samples/add_node.py#L38-L62) declares `pollers_enabled` to define the poller types to associate with the node, and whether each poller type is enabled or disabled.  Then it loops over the values in this list, adding each poller type to the specified node and either enabling or disabling it depending on how it was configured in `pollers_enabled`.

If you regularly configure nodes of the same type, you might want to configure one through the Orion website and inspect how the poller types are configured.  If that is satisfactory to you, you can edit `pollers_enabled` to match that and use those settings when you're configuring nodes of that type.  You could inspect `Orion.Pollers` for a particular node with a SWQL query like this:

```sql
SELECT TOP 1000
    PollerID,
    PollerType,
    NetObject,
    NetObjectType,
    NetObjectID,
    Enabled
FROM Orion.Pollers
WHERE NetObjectType = 'N' -- 'N' for node
    AND NetObjectID = 3 -- The particular node ID
```
