### ISSUE TITLE
Unmanage - Input string was not in a correct format

### ISSUE THREAD

**Issue by ajwillo** [solarwinds/orionsdk-python#6]
Hi,

no matter how I format the date for the unmanage function i get the same error as per below.

>>> swis.invoke('Orion.Nodes', 'Unmanage', netObjectId, '01-14-2017 00:00:00', '01-14-2017 06:00:00', True)
{u'Message': u'Input string was not in a correct format.', u'ExceptionType': u'System.FormatException', u'FullException': u'System.FormatException: Input string was not in a correct format.\r\n   at SolarWinds.InformationService.Verb.VerbExecutor.Invoke(Object hostInstance, Object[] parameters)\r\n   at SolarWinds.InformationService.Verb.VerbExecutorContext.Invoke()\r\n   at SolarWinds.InformationService.Core.InformationService.Invoke[T](String entity, String verb, Action`1 setupParameters, Func`2 extractReturnValue)'}

**Comment by nothrow** [comment]
@ajwillo, have you tried [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format? I just tested it with '2017-01-14T00:00:00' and it works for me.

**Comment by ajwillo** [comment]
same again?

>>> t = datetime(2017,01,14,00,00,00)
>>> e = datetime(2017,01,14,6,00,00)
>>> start = t.strftime("%Y-%m-%dT%H:%M:%S")
>>> end = e.strftime("%Y-%m-%dT%H:%M:%S")
>>> swis.invoke('Orion.Nodes', 'Unmanage', netObjectId, start, end, False)
{u'Message': u'Input string was not in a correct format.', u'ExceptionType': u'System.FormatException', u'FullException': u'System.FormatException: Input string was not in a correct format.\r\n   at SolarWinds.InformationService.Verb.VerbExecutor.Invoke(Object hostInstance, Object[] parameters)\r\n   at SolarWinds.InformationService.Verb.VerbExecutorContext.Invoke()\r\n   at SolarWinds.InformationService.Core.InformationService.Invoke[T](String entity, String verb, Action`1 setupParameters, Func`2 extractReturnValue)'}
>>>

**Comment by nothrow** [comment]
I just ran following:

```
import orionsdk

swis = orionsdk.SwisClient("localhost", "admin", "")
test = swis.invoke('Orion.Nodes', 'Unmanage', 'N:1', '2017-01-14T00:00:00', '2017-01-14T01:00:00', False)
print(test)
```

with output

```
E:\tmp\pytest>python a.py
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:843: I
nsecureRequestWarning: Unverified HTTPS request is being made. Adding certificat
e verification is strongly advised. See: https://urllib3.readthedocs.io/en/lates
t/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
None
```

against machine with NPM 12.0.1, and the code works as expected. What version of Orion are you using?

**Comment by ajwillo** [comment]
user error i had my node id as 'N:{636}' by accident, not 'N:636',
