### ISSUE TITLE
PollNode issues Fault

### ISSUE THREAD

**Issue by shadycuz** [solarwinds/orionsdk-python#7]
` swis.invoke('Orion.Nodes', 'PollNow', 'N' + nodeid)`

> 
{'Message': 'ProvideFault failed, check fault information.', 'ExceptionType': 'System.ServiceModel.FaultException`1[[SolarWinds.Orion.Core.Common.CoreFaultContract, SolarWinds.Orion.Channels, Version=10001.1.1.183, Culture=neutral, PublicKeyToken=null]]', 'FullException': 'System.ServiceModel.FaultException`1[SolarWinds.Orion.Core.Common.CoreFaultContract]: ProvideFault failed, check fault information. (Fault Detail is equal to SolarWinds.Orion.Core.Common.CoreFaultContract(Unknown): System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: N3685\r\nParameter name: entityIdentifier (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:\nSystem.ArgumentOutOfRangeException: N3685\r\nParameter name: entityIdentifier\n   at SolarWinds.Collector.Contract.Entity.DecomposeIdentifier(String entityIdentifier, String& netObjectType, Int32& id)\r\n   at SolarWinds.Collector.Repository.PollingDescriptionStoreInMemory.<EnumeratePollingDescription>d__c.MoveNext()\r\n   at SolarWinds.Collector.PollingController.PollingController.ResolveConditionRecursive(JobExecutionCondition condition, PollInformation pollInformation, UpdatePollingContextBehavior behavior)\r\n   at SolarWinds.Collector.PollingController.PollingController.JobNow(JobExecutionCondition condition, PollInformation pollInformation)\r\n   at SolarWinds.Collector.PollingController.PollingController.PollNow(String entityI...).'}

**Comment by tdanner** [comment]
Try this:

```
swis.invoke('Orion.Nodes', 'PollNow', 'N:' + nodeid)
```

**Comment by shadycuz** [comment]
`results = swis.invoke('Orion.Nodes', 'PollNow', 'N:' + nodeid)`
`print(results) `
`None `

Node status is unknown in the WebPanel. Untill I poll it from the node details page.

**Comment by tdanner** [comment]
PollNow just schedules the node for polling and then returns. So if you call it and then immediately go look at it in the website, it may not have actually been polled yet. What happens if you wait a minute and then look?

**Comment by shadycuz** [comment]
@tdanner I'm not sure =), but I have no doubt it works now that I got over my syntax error. Next time I bulk add some nodes I will have a bit more patience. Thanks for the help.

Levi
