### ISSUE TITLE
REQ: List all resources

### ISSUE THREAD

**Issue by shadycuz** [solarwinds/orionsdk-python#8]
https://thwack.solarwinds.com/thread/103617

Has this been implemented yet?

Thanks,
Levi

**Comment by tdanner** [comment]
It has not.

**Comment by shadycuz** [comment]
@tdanner I know you posted some workarounds on how you can use discovery and such to get by this and still have automation but I hope its something we see in the works soon for the API. I fee like it would be best for it to be native to the API instead having SWIS API and discovery API. 

Thanks,
Levi
