### ISSUE TITLE
400 Client Error: Specified cast is not valid

### ISSUE THREAD

**Issue by jwbensley** [solarwinds/orionsdk-python#9]
Hi Guys,

Im getting the following error when trying use the Python class to add a node to NPM that uses SNMPv3;

```
[mw@ansible-001 orion]$ python add_node.py
Add an SNMP v3 node:
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:340: SubjectAltNameWarning: Certificate for solarwinds-orion has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
Adding node 10.116.26.80... Traceback (most recent call last):
  File "add_node.py", line 138, in <module>
    main()
  File "add_node.py", line 96, in main
    results = swis.create('Orion.Nodes', **Orion_Nodes)
  File "/usr/lib/python2.7/site-packages/orionsdk/swisclient.py", line 34, in create
    "Create/" + entity, properties).json()
  File "/usr/lib/python2.7/site-packages/orionsdk/swisclient.py", line 59, in _req
    resp.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Specified cast is not valid. for url: https://solarwinds-orion:17778/SolarWinds/InformationService/v3/Json/Create/Orion.Nodes
```

This is my python script, its just to get a feel for the NPM API and this Python class:

```
[me@ansible-001 orion]$ cat add_node.py
from __future__ import print_function
import re
import requests
from orionsdk import SwisClient


def main():
   npm_server = 'SolarWinds-Orion'
   username = 'sw-user'
   password = 'sw-pass'


   swis = SwisClient(npm_server, username, password, verify="SolarWinds-Orion.pem")

   # Only need one of [DisplayName, Caption, NodeName]
   Orion_Nodes = {
      'DisplayName': "cpe",
      'Description': "cpe",
      'NodeDescription': "my cpe",
      'Location': "Lab",
      'UnManaged': False,
      'Allow64BitCounters': True,
      'ObjectSubType': "SNMP",
      'EngineID': 1,
      'IPAddress': "10.116.26.80",
      'SNMPVersion': '3',
      'SNMPV3Username': "snmpv3-user",
      'SNMPV3PrivMethod': "AES128",
      'SNMPV3PrivKeyIsPwd': True,
      'SNMPV3PrivKey': "snmpv3-priv-key",
      'SNMPV3AuthKey': "snmpv3-auth-key",
      'SNMPV3AuthMethod': "MD5",
      'SNMPV3AuthKeyIsPwd': True
   }

   print("Add an SNMP v3 node:")
   print("Adding node {}... ".format(Orion_Nodes['IPAddress']), end="")
   results = swis.create('Orion.Nodes', **Orion_Nodes)
   print("DONE!")

if __name__ == '__main__':
   main()
```
This node is actually added to SNMP however all the SNMPv3 details are missing, as per this screenshot:

![snmpv3](https://cloud.githubusercontent.com/assets/1025875/26050665/637dedc6-3957-11e7-855b-d43b1cc72768.png)

This is on `Orion Platform 2017.1, NPM 12.1`, I'm using Python 2.7.5. I can add the device manually through the web GUI using SNMPv3 without issue. I can also add the device using SNMP v2c via the GUI and API. It is just SNMPv3 via the API that is not working.

I can open a support case on the SW site too if that helps?

Please let me know what further info I can provide to help diagnose this issue.

**Comment by tdanner** [comment]
@TomasVrabel - I think you looked at a similar issue recently. Please check this one out.

**Comment by TomasVrabel** [comment]
Unfortunately there is a bug in the product. Boolean JSON True/False parameters are not processed correctly for SNMPv3 configuration.

As workaround I would recommend trying PowerShell, for PowerShell it should work.
You can find PS example for node creation here: https://github.com/solarwinds/OrionSDK/blob/master/Samples/PowerShell/CRUD.AddNode.ps1

Example of node properties:
```
$newNodeProps = @{
	DisplayName = "cde";
	Description = "cde";
	NodeDescription = "my cpe";
	Location =  "Lab";	
	UnManaged = $FALSE;
	Allow64BitCounters = $TRUE;
        ObjectSubType = "SNMP";
        IPAddress = "10.116.26.80";
        EngineID = 1;
	
        SNMPVersion = 3;
	SNMPV3Username = "snmpv3-user";
	SNMPV3PrivMethod = "AES128";
	SNMPV3PrivKeyIsPwd = $TRUE;
	SNMPV3PrivKey = "snmpv3-priv-key";
	SNMPV3AuthKey = "snmpv3-auth-key";
	SNMPV3AuthMethod = "MD5";
	SNMPV3AuthKeyIsPwd = $TRUE;
}
```

**Comment by jwbensley** [comment]
@TomasVrabel - Thanks for the your time here is greatly appreciated.

We use Ansible on Linux to automate our network operations so PowerShell isn't and option for us, plus Python is multi-OS so we'd rather stick with that as it can run on both Windows and Linux.

Is an internal bug case going to be opened for this so that it gets fixed?

**Comment by TomasVrabel** [comment]
I opened internal bug and we will track it under CORE-8580. You can use that number to check on the fix status.

**Comment by jwbensley** [comment]
Great, thanks @TomasVrabel !

**Comment by jwbensley** [comment]
@TomasVrabel  Hi guys, just checking, any update on this bug?

**Comment by tdanner** [comment]
This has been fixed for the next full release of NPM.

**Comment by jwbensley** [comment]
Thanks guys, we appreciate it!

**Comment by edurguti** [comment]
any time line on this?

**Comment by edurguti** [comment]
or is there a way we can set the credential names via python? ie already saved credential for snmp.
thanks

**Comment by tdanner** [comment]
NPM 12.2 is in beta now. https://thwack.solarwinds.com/message/368285

**Comment by tdanner** [comment]
> is there a way we can set the credential names via python? ie already saved credential for snmp.

Could you give a little more context about what you are trying to do?

**Comment by edurguti** [comment]
Thanks for the Beta, kind of hesitant to upgrade our production box.
example I have snmpv3 credentials saved and looking for a way to assign those programmatically when adding a node, instead of adding password/usernames/encryption keys every time I add a node.
Example:

snipped when adding a node through discovery (this is something im not interested in - I need to add them manually)

 snmpv3_credential_id = 90 -  this is my credential id for my snmpv3.

```
def main():
    npm_server = '1x'
    username = 'x'
    password = 'x'
    target_node_ip = '10.87.172.126'
    snmpv3_credential_id = 90
    orion_engine_id = 2


    swis = SwisClient(npm_server, username, password)
    print("Add an SNMP v3 node:")

    corePluginContext = {
    	'BulkList': [{'Address': target_node_ip}],
    	'Credentials': [
    		{
    			'CredentialID': snmpv3_credential_id,
    			'Order': 1
    		}
```

**Comment by edurguti** [comment]
is this going to be fixed under NPM 12.2? Thanks

**Comment by tdanner** [comment]
Yes, this is fixed in NPM 12.2.

**Comment by tdanner** [comment]
NPM 12.2 has been released with this bug fixed.

**Comment by edurguti** [comment]
only RC not GA

**Comment by tdanner** [comment]
https://support.solarwinds.com/Success_Center/Network_Performance_Monitor_(NPM)/NPM_12-2_release_notes

**Comment by edurguti** [comment]
well not it appears that there's another bug:
looks like the boolean for:
'SNMPv3AuthKeyIsPwd':
SNMPv3PrivKeyIsPwd
no matter what you set, false or true, it's always True which sucks.

**Comment by edurguti** [comment]
looks like if you set it to True (it actually  takes is as false) unless
I'm missing something

**Comment by tdanner** [comment]
I tried it out on my system using a variation of @jwbensley 's Python script from the top of this issue and it seem to work correctly with `True` or with `False`. Could you post your code?
